Update .github/workflows/openshift.yml
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -197,10 +197,10 @@ jobs:
         ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
         SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
       run: |
-        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        [[ -n "$ROUTE" ]] || (echo "Determining application route failed in previous step"; exit 1)
         echo
         echo "======================== Your application is available at: ========================"
-        echo ${{ env.ROUTE }}
+        echo "$ROUTE"
         echo "==================================================================================="
         echo
-        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+        echo "Your app can be taken down with: \"oc delete all --selector='$SELECTOR'\""
